/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppOrdenesRouteImport } from './routes/app.ordenes'
import { Route as AppNotificacionesRouteImport } from './routes/app.notificaciones'
import { Route as AppCategoriasRouteImport } from './routes/app.categorias'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminOrdenesRouteImport } from './routes/admin.ordenes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AppPublicacionesIndexRouteImport } from './routes/app.publicaciones.index'
import { Route as AppProductosIndexRouteImport } from './routes/app.productos.index'
import { Route as AppVendedorIdRouteImport } from './routes/app.vendedor.$id'
import { Route as AppPublicacionesNuevaRouteImport } from './routes/app.publicaciones.nueva'
import { Route as AppProductosIdRouteImport } from './routes/app.productos.$id'
import { Route as AdminUsuariosNuevoRouteImport } from './routes/admin.usuarios.nuevo'
import { Route as AdminUsuariosIdRouteImport } from './routes/admin.usuarios.$id'
import { Route as AppPublicacionesEditarIdRouteImport } from './routes/app.publicaciones.editar.$id'
import { Route as AdminUsuariosEditarIdRouteImport } from './routes/admin.usuarios.editar.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdenesRoute = AppOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdenesRoute = AdminOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AppPublicacionesIndexRoute = AppPublicacionesIndexRouteImport.update({
  id: '/publicaciones/',
  path: '/publicaciones/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosIndexRoute = AppProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendedorIdRoute = AppVendedorIdRouteImport.update({
  id: '/vendedor/$id',
  path: '/vendedor/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicacionesNuevaRoute = AppPublicacionesNuevaRouteImport.update({
  id: '/publicaciones/nueva',
  path: '/publicaciones/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosIdRoute = AppProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosNuevoRoute = AdminUsuariosNuevoRouteImport.update({
  id: '/usuarios/nuevo',
  path: '/usuarios/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosIdRoute = AdminUsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppPublicacionesEditarIdRoute =
  AppPublicacionesEditarIdRouteImport.update({
    id: '/publicaciones/editar/$id',
    path: '/publicaciones/editar/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AdminUsuariosEditarIdRoute = AdminUsuariosEditarIdRouteImport.update({
  id: '/usuarios/editar/$id',
  path: '/usuarios/editar/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/ordenes': typeof AdminOrdenesRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/productos': typeof AdminProductosRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/ordenes': typeof AppOrdenesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/nuevo': typeof AdminUsuariosNuevoRoute
  '/app/productos/$id': typeof AppProductosIdRoute
  '/app/publicaciones/nueva': typeof AppPublicacionesNuevaRoute
  '/app/vendedor/$id': typeof AppVendedorIdRoute
  '/app/productos/': typeof AppProductosIndexRoute
  '/app/publicaciones/': typeof AppPublicacionesIndexRoute
  '/admin/usuarios/editar/$id': typeof AdminUsuariosEditarIdRoute
  '/app/publicaciones/editar/$id': typeof AppPublicacionesEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/ordenes': typeof AdminOrdenesRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/productos': typeof AdminProductosRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/ordenes': typeof AppOrdenesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/nuevo': typeof AdminUsuariosNuevoRoute
  '/app/productos/$id': typeof AppProductosIdRoute
  '/app/publicaciones/nueva': typeof AppPublicacionesNuevaRoute
  '/app/vendedor/$id': typeof AppVendedorIdRoute
  '/app/productos': typeof AppProductosIndexRoute
  '/app/publicaciones': typeof AppPublicacionesIndexRoute
  '/admin/usuarios/editar/$id': typeof AdminUsuariosEditarIdRoute
  '/app/publicaciones/editar/$id': typeof AppPublicacionesEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/ordenes': typeof AdminOrdenesRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/productos': typeof AdminProductosRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/ordenes': typeof AppOrdenesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/nuevo': typeof AdminUsuariosNuevoRoute
  '/app/productos/$id': typeof AppProductosIdRoute
  '/app/publicaciones/nueva': typeof AppPublicacionesNuevaRoute
  '/app/vendedor/$id': typeof AppVendedorIdRoute
  '/app/productos/': typeof AppProductosIndexRoute
  '/app/publicaciones/': typeof AppPublicacionesIndexRoute
  '/admin/usuarios/editar/$id': typeof AdminUsuariosEditarIdRoute
  '/app/publicaciones/editar/$id': typeof AppPublicacionesEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot'
    | '/login'
    | '/register'
    | '/admin/categorias'
    | '/admin/ordenes'
    | '/admin/perfil'
    | '/admin/productos'
    | '/app/categorias'
    | '/app/notificaciones'
    | '/app/ordenes'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/nuevo'
    | '/app/productos/$id'
    | '/app/publicaciones/nueva'
    | '/app/vendedor/$id'
    | '/app/productos/'
    | '/app/publicaciones/'
    | '/admin/usuarios/editar/$id'
    | '/app/publicaciones/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/register'
    | '/admin/categorias'
    | '/admin/ordenes'
    | '/admin/perfil'
    | '/admin/productos'
    | '/app/categorias'
    | '/app/notificaciones'
    | '/app/ordenes'
    | '/app/perfil'
    | '/admin'
    | '/app'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/nuevo'
    | '/app/productos/$id'
    | '/app/publicaciones/nueva'
    | '/app/vendedor/$id'
    | '/app/productos'
    | '/app/publicaciones'
    | '/admin/usuarios/editar/$id'
    | '/app/publicaciones/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot'
    | '/login'
    | '/register'
    | '/admin/categorias'
    | '/admin/ordenes'
    | '/admin/perfil'
    | '/admin/productos'
    | '/app/categorias'
    | '/app/notificaciones'
    | '/app/ordenes'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/nuevo'
    | '/app/productos/$id'
    | '/app/publicaciones/nueva'
    | '/app/vendedor/$id'
    | '/app/productos/'
    | '/app/publicaciones/'
    | '/admin/usuarios/editar/$id'
    | '/app/publicaciones/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ordenes': {
      id: '/app/ordenes'
      path: '/ordenes'
      fullPath: '/app/ordenes'
      preLoaderRoute: typeof AppOrdenesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificaciones': {
      id: '/app/notificaciones'
      path: '/notificaciones'
      fullPath: '/app/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ordenes': {
      id: '/admin/ordenes'
      path: '/ordenes'
      fullPath: '/admin/ordenes'
      preLoaderRoute: typeof AdminOrdenesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/publicaciones/': {
      id: '/app/publicaciones/'
      path: '/publicaciones'
      fullPath: '/app/publicaciones/'
      preLoaderRoute: typeof AppPublicacionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/productos/': {
      id: '/app/productos/'
      path: '/productos'
      fullPath: '/app/productos/'
      preLoaderRoute: typeof AppProductosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendedor/$id': {
      id: '/app/vendedor/$id'
      path: '/vendedor/$id'
      fullPath: '/app/vendedor/$id'
      preLoaderRoute: typeof AppVendedorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publicaciones/nueva': {
      id: '/app/publicaciones/nueva'
      path: '/publicaciones/nueva'
      fullPath: '/app/publicaciones/nueva'
      preLoaderRoute: typeof AppPublicacionesNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/productos/$id': {
      id: '/app/productos/$id'
      path: '/productos/$id'
      fullPath: '/app/productos/$id'
      preLoaderRoute: typeof AppProductosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios/nuevo': {
      id: '/admin/usuarios/nuevo'
      path: '/usuarios/nuevo'
      fullPath: '/admin/usuarios/nuevo'
      preLoaderRoute: typeof AdminUsuariosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios/$id': {
      id: '/admin/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminUsuariosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/publicaciones/editar/$id': {
      id: '/app/publicaciones/editar/$id'
      path: '/publicaciones/editar/$id'
      fullPath: '/app/publicaciones/editar/$id'
      preLoaderRoute: typeof AppPublicacionesEditarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios/editar/$id': {
      id: '/admin/usuarios/editar/$id'
      path: '/usuarios/editar/$id'
      fullPath: '/admin/usuarios/editar/$id'
      preLoaderRoute: typeof AdminUsuariosEditarIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminOrdenesRoute: typeof AdminOrdenesRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsuariosIdRoute: typeof AdminUsuariosIdRoute
  AdminUsuariosNuevoRoute: typeof AdminUsuariosNuevoRoute
  AdminUsuariosEditarIdRoute: typeof AdminUsuariosEditarIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminOrdenesRoute: AdminOrdenesRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsuariosIdRoute: AdminUsuariosIdRoute,
  AdminUsuariosNuevoRoute: AdminUsuariosNuevoRoute,
  AdminUsuariosEditarIdRoute: AdminUsuariosEditarIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppOrdenesRoute: typeof AppOrdenesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductosIdRoute: typeof AppProductosIdRoute
  AppPublicacionesNuevaRoute: typeof AppPublicacionesNuevaRoute
  AppVendedorIdRoute: typeof AppVendedorIdRoute
  AppProductosIndexRoute: typeof AppProductosIndexRoute
  AppPublicacionesIndexRoute: typeof AppPublicacionesIndexRoute
  AppPublicacionesEditarIdRoute: typeof AppPublicacionesEditarIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppOrdenesRoute: AppOrdenesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductosIdRoute: AppProductosIdRoute,
  AppPublicacionesNuevaRoute: AppPublicacionesNuevaRoute,
  AppVendedorIdRoute: AppVendedorIdRoute,
  AppProductosIndexRoute: AppProductosIndexRoute,
  AppPublicacionesIndexRoute: AppPublicacionesIndexRoute,
  AppPublicacionesEditarIdRoute: AppPublicacionesEditarIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
